
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cube
 */
public class ShowInvoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form ShowInvoice
     */
   
     private ArrayList<Person> invoices;
    /**
     * Creates new form AddInvoice
     */
    public ShowInvoice(ArrayList<Person> invoices) {
        initComponents();
        this.invoices = invoices;
        for(int i = 0; i< this.invoices.size(); i++){
            Person invoice = invoices.get(i);
            jTextArea1.append(invoice.getClient()+" "+invoice.getAdress()+ " "+ invoice.getProblem()+"\n");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Просмотр всех заявок");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
